# Generated by Django 2.2.16 on 2020-09-30 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'instytucja', 'verbose_name_plural': 'instytucje'},
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='liczba worków')),
                ('adress', models.CharField(max_length=64, verbose_name='ulica, nr domu, nr lokalu')),
                ('phone_number', models.IntegerField(verbose_name='numer telefonu')),
                ('city', models.CharField(max_length=64, verbose_name='miasto')),
                ('zip_code', models.IntegerField(verbose_name='kod pocztwy xx-xxx')),
                ('pick_up_date', models.DateField(null=True, verbose_name='data odbioru')),
                ('pick_up_time', models.TimeField(null=True, verbose_name='godzina odbioru')),
                ('pick_up_comment', models.TextField(verbose_name='uwagi dla kuriera')),
                ('categories', models.ManyToManyField(to='donations.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='donations.Institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
